extends: airbnb-base
rules:
    indent:
    - error
    - 4
    linebreak-style:
    - error
    - unix
    quotes:
    - error
    - single
    semi:
    - error
    - always
    comma-dangle:
    - error
    - always-multiline
    no-cond-assign:
    - error
    - always
    no-console: 'off'
env:
    jasmine: true

